# current state: disable internal

# internal
monitor = eDP-1, disable
# monitor = HDMI-A-1, 3840x2160@60, 1600x0, 2
# Home
monitor = desc:Philips Consumer Electronics Company PHL 27E1N5900 UK82242002107, 3840x2160@60, 1600x0, 2
# dormitary
monitor = desc:Beihai Century Joint Innovation Technology Co.Ltd P275MV PLUS 0000000000000, 3840x2160@160, 1600x0, 2
monitor = desc:LG Electronics LG ULTRAFINE 209NTKF7U037, 3840x2160@60, 1600x0, 2


input {
  force_no_accel = 1
}
