[ids]

*

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = esc
# Remaps the escape key to capslock
# esc = capslock

capslock = overload(nav, esc)
esc = capslock

[nav]
h = left
j = down
k = up
l = right
