
$background = rgba(131318ff)
$backgroundAlpha = 131318

$error = rgba(ffb4abff)
$errorAlpha = ffb4ab

$error_container = rgba(93000aff)
$error_containerAlpha = 93000a

$inverse_on_surface = rgba(313036ff)
$inverse_on_surfaceAlpha = 313036

$inverse_primary = rgba(5b5891ff)
$inverse_primaryAlpha = 5b5891

$inverse_surface = rgba(e5e1e9ff)
$inverse_surfaceAlpha = e5e1e9

$on_background = rgba(e5e1e9ff)
$on_backgroundAlpha = e5e1e9

$on_error = rgba(690005ff)
$on_errorAlpha = 690005

$on_error_container = rgba(ffdad6ff)
$on_error_containerAlpha = ffdad6

$on_primary = rgba(2c2960ff)
$on_primaryAlpha = 2c2960

$on_primary_container = rgba(e3dfffff)
$on_primary_containerAlpha = e3dfff

$on_primary_fixed = rgba(17134aff)
$on_primary_fixedAlpha = 17134a

$on_primary_fixed_variant = rgba(434078ff)
$on_primary_fixed_variantAlpha = 434078

$on_secondary = rgba(302e42ff)
$on_secondaryAlpha = 302e42

$on_secondary_container = rgba(e3e0f9ff)
$on_secondary_containerAlpha = e3e0f9

$on_secondary_fixed = rgba(1b1a2cff)
$on_secondary_fixedAlpha = 1b1a2c

$on_secondary_fixed_variant = rgba(464559ff)
$on_secondary_fixed_variantAlpha = 464559

$on_surface = rgba(e5e1e9ff)
$on_surfaceAlpha = e5e1e9

$on_surface_variant = rgba(c8c5d0ff)
$on_surface_variantAlpha = c8c5d0

$on_tertiary = rgba(472638ff)
$on_tertiaryAlpha = 472638

$on_tertiary_container = rgba(ffd8e9ff)
$on_tertiary_containerAlpha = ffd8e9

$on_tertiary_fixed = rgba(2f1123ff)
$on_tertiary_fixedAlpha = 2f1123

$on_tertiary_fixed_variant = rgba(603b4fff)
$on_tertiary_fixed_variantAlpha = 603b4f

$outline = rgba(928f99ff)
$outlineAlpha = 928f99

$outline_variant = rgba(47464fff)
$outline_variantAlpha = 47464f

$primary = rgba(c4c0ffff)
$primaryAlpha = c4c0ff

$primary_container = rgba(434078ff)
$primary_containerAlpha = 434078

$primary_fixed = rgba(e3dfffff)
$primary_fixedAlpha = e3dfff

$primary_fixed_dim = rgba(c4c0ffff)
$primary_fixed_dimAlpha = c4c0ff

$scrim = rgba(000000ff)
$scrimAlpha = 000000

$secondary = rgba(c7c4dcff)
$secondaryAlpha = c7c4dc

$secondary_container = rgba(464559ff)
$secondary_containerAlpha = 464559

$secondary_fixed = rgba(e3e0f9ff)
$secondary_fixedAlpha = e3e0f9

$secondary_fixed_dim = rgba(c7c4dcff)
$secondary_fixed_dimAlpha = c7c4dc

$shadow = rgba(000000ff)
$shadowAlpha = 000000

$source_color = rgba(5f5ab5ff)
$source_colorAlpha = 5f5ab5

$surface = rgba(131318ff)
$surfaceAlpha = 131318

$surface_bright = rgba(3a383fff)
$surface_brightAlpha = 3a383f

$surface_container = rgba(201f25ff)
$surface_containerAlpha = 201f25

$surface_container_high = rgba(2a292fff)
$surface_container_highAlpha = 2a292f

$surface_container_highest = rgba(35343aff)
$surface_container_highestAlpha = 35343a

$surface_container_low = rgba(1c1b21ff)
$surface_container_lowAlpha = 1c1b21

$surface_container_lowest = rgba(0e0e13ff)
$surface_container_lowestAlpha = 0e0e13

$surface_dim = rgba(131318ff)
$surface_dimAlpha = 131318

$surface_tint = rgba(c4c0ffff)
$surface_tintAlpha = c4c0ff

$surface_variant = rgba(47464fff)
$surface_variantAlpha = 47464f

$tertiary = rgba(eab9d1ff)
$tertiaryAlpha = eab9d1

$tertiary_container = rgba(603b4fff)
$tertiary_containerAlpha = 603b4f

$tertiary_fixed = rgba(ffd8e9ff)
$tertiary_fixedAlpha = ffd8e9

$tertiary_fixed_dim = rgba(eab9d1ff)
$tertiary_fixed_dimAlpha = eab9d1

