[mgr]
prepend_keymap=[
  { on = [ "g", "d" ], run = "cd ~/Downloads" },
  { on = [ "g", "D" ], run = "cd ~/Documents/" },
  { on = [ "g", "v" ], run = "cd ~/Videos/" },
  { on = [ "g", "m" ], run = "cd ~/Music/" },
  { on = [ "g", "P" ], run = "cd ~/Pictures/" },
  { on = [ "g", "." ], run = "cd ~/.dotfiles" },
  { on = [ "g", "," ], run = "cd ~/.config" },
	{ on = [ "g", "/" ], run = "cd /" },
	{ on = [ "g", "l" ], run = "cd ~/Documents/sync-server/Latex/" },
	{ on = [ "g", "c" ], run = "cd ~/Documents/sync-server/c/" },
	{ on = [ "g", "p" ], run = "cd ~/Documents/sync-server/Latex/pdfs/" },
	{ on = [ "g", "s" ], run = "cd ~/Documents/deng_server/" },
	{ on = [ "g", "S" ], run = "cd ~/Documents/sync-server/" },
	{ on = [ "g", "T" ], run = "cd /home/fireond/.local/share/Trash/" },
	{ on = [ "g", "C" ], run = "cd ~/Documents/Codes/" },
	{ on = [ "g", "r" ], run = '''
	shell 'ya pub dds-cd --str "$(git rev-parse --show-toplevel)"' --confirm
''' },

  { on = [ "T" ], run = "plugin max-preview" },
  { on = [ "C" ], run = "plugin ouch 7z", desc = "Compression with ouch" },

  { on = "o", run = "open --interactive" },
  { on = "O", run = '''
  shell 'qlmanage -p "$@"' --confirm
''' },

  # plugins
	{ on = [ "l" ], run = "plugin smart-enter" },
	{ on = [ "k" ], run = "plugin arrow '-1'" },
	{ on = [ "j" ], run = "plugin arrow '1'" },
	{ on = [ "s" ], run = "plugin fzf" },
  { on = [ "<C-y>" ], run = "plugin wl-clipboard" },
  { on = [ "M" ], run = "plugin mount" },
  { on   = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" }
]
