[mgr]
sort_by = "mtime"
sort_reverse = true
show_hidden = true
linemode = "size_and_mtime"


[preview]
max_width = 1000
max_height = 2000

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'auto_padding_nvim.sh "$@"', desc = "nvim", block = true, for = "unix" },
]
sioyek = [
  { run = 'nohup sioyek "$@" > /dev/null 2>&1 &', desc = "sioyek", orphan = true, for = "unix" },
]
zathura = [
  { run = 'nohup zathura "$@" > /dev/null 2>&1 &', desc = "zathura", orphan = true, for = "linux" },
]
qimgv = [
  { run = 'nohup qimgv "$@" > /dev/null 2>&1 &', desc = "qimgv", orphan = true, for = "linux" },
]
inkscape = [
  { run = 'nohup inkscape "$@" > /dev/null 2>&1 &', desc = "inkscape", orphan = true, for = "linux" },
]

[open]
prepend_rules = [
  { name = "*.pdf", use = ["zathura"] },
  { name = "*.tex", use = "edit" },
  { name = "*.svg", use = "inkscape" },
  { mime = "image/*", use = ["open", "qimgv", "reveal"] },
]
