[mgr]
sort_by = "mtime"
sort_reverse = true
show_hidden = true
linemode = "size_and_mtime"


[preview]
max_width = 1000
max_height = 2000

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'auto_padding_nvim.sh "$@"', desc = "nvim", block = true, for = "unix" },
]
sioyek = [
  { run = 'nohup sioyek "$@" > /dev/null 2>&1 &', desc = "sioyek", orphan = true, for = "unix" },
]
zathura = [
  { run = 'nohup zathura "$@" > /dev/null 2>&1 &', desc = "zathura", orphan = true, for = "linux" },
]
qimgv = [
  { run = 'nohup qimgv "$@" > /dev/null 2>&1 &', desc = "qimgv", orphan = true, for = "linux" },
]
inkscape = [
  { run = 'nohup inkscape "$@" > /dev/null 2>&1 &', desc = "inkscape", orphan = true, for = "linux" },
]
# wps = [
#   { run = 'env XMODIFIERS="@im=fcitx" QT_IM_MODULE="fcitx5" /usr/bin/wps "$@"', orphan = false, desc = "wps", for = "linux" },
# ]
wps = [
  { run = """bash -c '
      set -e
      for f in "$@"; do
        d="$(dirname "$f")"
        b="$(basename "$f")"
        # 进到文件所在目录，用相对路径调用 wps（规避绝对路径 bug）
        ( cd "$d" && exec env XMODIFIERS="@im=fcitx" QT_IM_MODULE="fcitx5" /usr/bin/wps "./$b" ) &
      done
    ' _ $@""", desc = "WPS (debug foreground)", orphan = false, block  = true, for    = "unix" }
]

[open]
prepend_rules = [
  { name = "*.pdf", use = ["zathura"] },
  { name = "*.tex", use = "edit" },
  { name = "*.svg", use = "inkscape" },
  { name = "*.doc", use = "wps" },
  { name = "*.docx", use = "wps" },
  { name = "*.xls", use = "wps" },
  { name = "*.xlsx", use = "wps" },
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", use = "wps" },
  { mime = "image/*", use = ["open", "qimgv", "reveal"] },
]
