#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.15
yabai -m config active_window_opacity 1.00
yabai -m config normal_window_opacity 0.90
yabai -m config insert_feedback_color 0xff9dd274
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config external_bar all:38:0

# general space settings
yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8


# auto focus window below cursor
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# if need to disable specific app
# yabai -m signal --add label=on_dest_refocus event=window_destroyed app!='Maccy' \
#       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add  label=on_min_refocus event=window_minimized app!='Maccy' \
#       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add  label=on_hide_refocus event=application_hidden app!='Maccy' \
#       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add  label=on_term_refocus event=application_terminated app!='Maccy' \
#       action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"


# signal with sketchybar
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
# disable specific apps
disabled_apps=(
    "^System Settings$"
    "^Calculator$"
    "^Karabiner-Elements$"
    "^QuickTime Player$"
    "^WeChat$"
    "^HapiGo$"
    "^360压缩大师$"
    "^Font Book$"
    "^NeatDownloadManager$"
    "^NetEaseMusic$"
    "^MonitorControl$"
    "^Tencent Lemon$"
    "^Snipaste$"
    "^AlDente$"
    "^DesktopLauncher$"
    "^Loader$"
    # "^ChatGPT$"
)

for app in "${disabled_apps[@]}"; do
    yabai -m rule --add app="$app" manage=off
done

# yabai -m rule --add app="^Preview$" title="^(?!.*pdf).*" manage=off


border_options=(
  style=round
  # style=square
  width=6.0
  hidpi=on
	active_color=0xffe2e2e3
	 inactive_color=0xff414550
  # active_color=0xff8a866e
  # background_color=0xff81969e
  blacklist="Safari,iPhone Mirroring,Steam Helper,Microsoft PowerPoint"
  blur_radius=5
)

# borders "${border_options[@]}"

echo "yabai configuration loaded.."
